### PR TITLE
List all network interfaces in master chooser

### PR DESCRIPTION
**Pull request by tulku**
A list of detected network interfaces can be found in the advanced
options segment of the master chooser UI. Selecting an interface allows
the user to configure the ROS Hostname. If no interface is selected then
the code fall-back to the previous behaviour.

I made a simple modifications to the pubsub example to show how the
RosHostname can be used in the applications.

This pull request supersedes https://github.com/rosjava/android_core/pull/183

### CODE REVIEW

**Comment by tulku** [comment]
@damonkohler I've rebased it to master. I hope that there are no lingering style issues and this can be merged. Thanks!

**Comment by tulku** [comment]
@damonkohler I've noticed that you pushed some changes to MasterChooser which conflicts with this PR. I'll be doing a new rebase to master, and creating a new PR later today.

**Comment by tulku** [comment]
Sorry for the merge @damonkohler, I hope you can merge this into master to prevent further conflicts.

**Comment by tulku** [comment]
@damonkohler were you able to take a look at this? If you can't take this now, could  @stonier  do it?

**Comment by stonier** [comment]
@tulku sorry mate, some long waiting merges went in on top of your rebase. Could you give it another shot? Then I'll take a look

**Comment by tulku** [comment]
@stonier, @adamantivm just merged with master. Sorry it's not a rebase, I hope it can be merged now, to avoid future conflicts.

**Comment by tulku** [comment]
@stonier, could this be merged now?

**Comment by stonier** [comment]
Took this for a test run with the pubsub tutorial on my galaxy mega and have some usability questions. First of all, what I'm seeing after I click on 'Show Advanced Options' is three network interfaces - rmnet0, wlan0, p2p0. 
- Even after I select one, there is no way of visually knowing which one I have selected.
  - When I select one, the text comes up with an orange background, but nothing stays highlighted.
  - Is this the intended behaviour or is it my phone?
- If I choose wlan0 and new public master, it works.
  - I can check my router's web url to see my android's ip, set ROS_MASTER_URI on the pc and do a `rostopic echo /chatter` there
  - But this is an inconvenient way to figure out the ip.
  - Is there a better way to work this out? Can it be displayed?
- Should the pubsub tutorial and master both shutdown when 'back'ing out of the application?
  - I have to currently go into android dashboard and 'tap to shutdown'.

**Comment by tulku** [comment]
Thanks for the comments @stonier!

Regarding the lack of feedback, it is as you describe. It used to show a toast indicating that the interface was selected, but was later removed. I could look into highlighting the selected interface permanently.

I don't quite understand the problems with the AP. This is not a "simpler" way of knowing the IP of the phone. Rather it allows to choose from which interface we want to connect (or create) to the ROS network. Cell phones can have multiple IPs, in multiple interfaces, and current master chooser always use the first interface available.

In particular we are interested in connecting to a ROS Master through a VPN and not through the wlan0 IP. This allows us to maintain the connection between the robot and the client using cellular network when wifi is not available. In those cases we select tun0 instead of wlan0.

There were some changes to android_core which produced the behaviour that you describe when closing the app. Now we even need to add a new permission to the ROS apps to be able to show the alert before closing. This closing confirmation (and tapping the notification to close) is not part of this commit.

**Comment by damonkohler** [comment]
This PR is really old. In the interest of progress, I'm merging it in.

In a follow up PR, please
- highlight the selected interface and
- display the ROS master URI.

You can display the URI in a confirmation dialog after clicking "new master."

**Comment by tulku** [comment]
I don't think we should show the Master URI after clicking in the New Master. We needed the Master URI to be very visible, and we solved it showing the URI in the main application UI instead on a pop up, and is constantly present.
This makes it very easy to connect a phone to the robot, at any moment.

**Pull request merged**
