### PR TITLE
Migration to Gradle 1.11

### PR DESCRIPTION
**Pull request by DmitryDzz**
https://github.com/rosjava/android_core/issues/198

### CODE REVIEW

**Comment by stonier** [comment]
Do you actually need `19.0.3` yet? I typically wait until a new minor version comes out and then lock it one minor version below this as it most likely won't get updated (or not very frequently).

Less trouble for us to keep chasing then.

**Comment by stonier** [comment]
If we do update the buildToolsVersion it would be better updated over in https://github.com/rosjava/rosjava_bootstrap (specifically [RosAndroid.groovy](https://github.com/rosjava/rosjava_bootstrap/blob/hydro/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosAndroid.groovy)). Putting it in every build.gradle makes it difficult to update everywhere in the future.

**Comment by ollide** [comment]
I don't think that `19.0.3` offers any stunning advantages for us, but still it is a requirement for the Android Gradle plugin (starting with 0.9). Using the latest version of Android Studio brings huge advantages and developers benefit a lot from it. We should at least offer them the ability to easily use the most recent version!

It's a good thing that the `buildToolsVersion` is set centrally but there are still so many `build.gradle` and `gradle-wrapper.properties` files needed to be changed when upgrading, which makes the whole process a bit tiring.

**Comment by stonier** [comment]
Definitely...if `19.0.3` is required on 0.5.1 then that's a very good reason to upgrade here in rosjavaland.
I just downloaded the new android studio 30mins ago and will take it for a run tonight.

> so many build.gradle and gradle-wrapper.properties files needed to be changed when upgrading, which makes the whole process a bit tiring.

Yeah, this is true. I don't have a solution for that, however it should slow down - gradle doesn't usually require such aggressive upgrades, but that's simply because android studio is hammering through an aggressive upgrade plan right now.

**Comment by ollide** [comment]
I agree that it will slow down. The fact that plugin version 0.9.+ supports Gradle 1.10 and 1.11 is a good sign, though.

If you start upgrading you might encounter some duplicated license files build errors (which were discussed in several issues here). Gradle Android plugin 0.9.1 brings a new solution to this:

> It's now possible to include a file when there's a conflict during packaging:
> 
> ```
> android.packagingOptions {
>     pickFirst 'META-INF/foo.txt'
> }
> ```

I think this is much better than simply [excluding](https://github.com/stonier/android_extras/commit/5d9ac1534693de4430cac5faa5388df57af43738) them.

**Comment by stonier** [comment]
Thanks for the heads up on the packaging options, I'll update them when I get a chance.

**Comment by stonier** [comment]
I'll merge the appropriate changes in on the command line separately as I don't want to have the buildToolsVersion dropping into each and every `build.gradle` file.

**Comment by stonier** [comment]
In 812d66eaa1b97dd6db436786682adf695d1eb5ef

**Pull request closed without merging**
