### PR TITLE
Upgrades Gradle Wrapper to version 1.8.

### PR DESCRIPTION
**Pull request by damonkohler**
Also removes redundant specification in .gitignore file.

### CODE REVIEW

**Comment by adamantivm** [comment]
FWIW, I spent the day getting this (alongside with our projects) to build.
For the most part it works, the only two things to note are:
- I had to specify the buildscript classpath in the project build file, otherwise it would fail to build packages that included android-library projects. e.g. https://github.com/creativa77/base_controller/pull/2/files
- It may be worth mentioning the new requirement on Android Build Tools 18.1.1 in the upgrade docs - dumb people like myself may save time figuring out the errors arising from the missing dependency

**Comment by damonkohler** [comment]
On your first point, I'll try to reproduce the issue. On the second, we're working on a better approach to documentation :)

**Comment by stonier** [comment]
What error did you see Julian? Might be worth adding that to the [faq](http://wiki.ros.org/android/FAQ).

**Comment by adamantivm** [comment]
I'm trying to reproduce this at the moment, it was an error specifically when trying to import into Android Studio - catkin_make was working fine.

**Comment by adamantivm** [comment]
Ok, here it goes.

What I'm doing is taking android_core with these updates applied, make sure it's not already imported to Android Studio (i.e.: `rm -Rf .idea; find . -name "*.iml" | xargs rm`) and, after finishing a good successful catkin_make, trying to import into Android Studio 0.3.0

I get the following error: https://gist.github.com/adamantivm/7105760

Which shows up in the UI like so:
screenshot73

This goes away if I manually add the gradle 0.6.+ classpath to the buildscripts section for subprojects in the main project gradle.build file (or individually on each subproject):

```
...
        buildscript {
            dependencies {
                classpath 'com.android.tools.build:gradle:0.6.1'
            }
        }
...
```

The same happens in other packages for me.

I am not sure why this is happening though: from my meager understanding of the ros-android plug-in (for which I already applied @damonkohler's update) it seems like it should already be doing exactly that. Puzzling.

**Comment by stonier** [comment]
If it goes away when you add the buildscript classpath in, then I think perhaps you are getting the wrong rosjava_bootstrap/gradle_plugins artifact. 

Do you have rosjava_bootstrap (master branch) in your source workspace? The debs and current rosjava_mvn_repo has only artifacts from hydro builds atm, so if you tell it to get the latest from there it would be using a buildscript looking for 0.5.6.

I'll backport these changes to hydro once we've verified that there's no problems on the master branches.

**Comment by adamantivm** [comment]
I agree that is a possibility, but I don't understand how.
I have master rosjava_bootstrap with Damon's fixes applied. I even went
through the trouble of wiping the local and catkin maven repos.
Can you think of a reliable way to tell which rosjava_bootstrap artifact is
getting used during the import?

**Comment by stonier** [comment]
Hmm...just realised we forgot to bump the version of rosjava_bootstrap as well. That may be causing a problem for you in as much as it didn't update the artifact because it has the same version number. Still, if you wiped the catkin_maven_repos, it should have just built into them.

Can you bump the version number in rosjava_bootstrap/package.xml and test? I don't have an android workspace on this computer.

**Comment by adamantivm** [comment]
Ah HA!

So yes, that was part of the problem, but only part. The other thing is
that since we're now using the maven repos from the catkin workspace, I
need to start Android Studio from a console in which
catkin_ws/devel/setup.bash has been sourced, which didn't use to be
necessary.

After bumping the version number of rosjava_bootstrap to 0.1.8, requiring
that specific version from my project AND making sure I launched Android
Studio after sourcing the proper setup.bash file, I was able to import the
project without the need for manually specifying the buildscript classpath.

I also reproduced the error message you get when you don't have the proper
Android SDK Build-Tools, which I was planning to write in the ROS wiki as
another troubleshooting link to the FAQ until the ROS wiki stopped
responding to me  :-/

So I guess that means this patch should be enough, no? I still think it may
be a good idea to bump the version of rosjava_boostrap though.

On Tue, Oct 22, 2013 at 6:23 PM, Daniel Stonier notifications@github.comwrote:

> Hmm...just realised we forgot to bump the version of rosjava_bootstrap as
> well. That may be causing a problem for you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rosjava/android_core/pull/176#issuecomment-26851881
> .

## 

-- Julian Cerruti

**Comment by adamantivm** [comment]
Here's my meager contribution to the documentation (point 2 in my original comment to Damon), let me know if you think it's acceptable and I can link it from android/FAQ: http://wiki.ros.org/android/FAQ/buildToolsRevision

**Comment by stonier** [comment]
Great!

I'll bump the version in rosjava_bootstrap now. Link that page in http://wiki.ros.org/android/FAQ as well.

**Comment by stonier** [comment]
Merging this one since testing has proved ok.

**Comment by stonier** [comment]
Rosjava bootstrap [version bump](https://github.com/rosjava/rosjava_bootstrap/pull/8).

**Pull request merged**
