### PR TITLE
Add AppCompatRosActivity class

### PR DESCRIPTION
**Pull request by PerrineAguiar**
This PR adds a  AppCompatRosActivity class.
This allows to use RosActivity with the [android support library](https://developer.android.com/topic/libraries/support-library/features.html).

@adamantivm ptal.

### CODE REVIEW

**Comment by adamantivm** [comment]
@PerrineAguiar thanks so much for this contribution. One question: did you try building this project after this file is added? I imagine we would also require to list the additional support lib dependencies in build.gradle, no?

**Comment by PerrineAguiar** [comment]
@adamantivm I updated the gradle dependencies. Unfortunately I have troubles building the android_10 project in android studio, so I was not able to test if these changes are compiling.
Do you think you can try to build it?

**Comment by adamantivm** [comment]
@PerrineAguiar thank you for the update. I see you changed the target SDK version from 10 to 22, but the projects in `android_10` like the name suggest have been kept so far this way so as to make it backwards compatible all the way to SDK 10, so that change will break that assumption.
Is 22 the lowest possible SDK version that is supported by the support library? If it could be lowered to say 15, then we could place this activity in `android_15` instead. What do you think?

**Comment by PerrineAguiar** [comment]
@adamantivm Thanks for the explanation.
According to the [android doc](https://developer.android.com/topic/libraries/support-library/index.html#api-versions): "Starting with Support Library version 24.2.0 (released in August 2016), the minimum supported API level has changed to Android 2.3 (API level 9) for all support library packages".
So targeting SDK version 10 should be fine.

**Comment by adamantivm** [comment]
Ah, great! I'll try to have myself or @jubeira test if this builds fine and then it's good to go.
@HelloEgg if you are interested in trying this out it would also be helpful.

**Comment by adamantivm** [comment]
So trying to build this as is yields exactly on the errors reported by @HelloEgg in #248 
This is because it is necessary to use the same SDK to build than the version of support library used, in this case version 25.
After updating `compileSdkVersion` to 25, the next error is that `notification.setEventInfo` has been deprecated, so it needs to be replaced by a builder [as explained here](http://stackoverflow.com/questions/16852270/how-to-implement-the-deprecated-methods-of-notification)

**Comment by adamantivm** [comment]
I am the other committer and I am OK with contributing @googlebot

**Comment by adamantivm** [comment]
@PerrineAguiar so the only missing bit was updating compileSdkVersion to a version compatible to the support library version.
I downgraded the support library used to version 22 because version 23 introduces an API change that would require changing some code. I think version 22 (Android 5.1.1) is sufficiently high for recent builds. We can think of updating beyond 22 at some point in the future.

@PerrineAguiar @jubeira could you give me your opinion on this change? If you both agree, we could merge the addition.

@HelloEgg FYI.

**Comment by PerrineAguiar** [comment]
@adamantivm Thanks for completing this work.
I agree with using version 22 of the support library.

**Comment by jubeira** [comment]
@PerrineAguiar @adamantivm I had no problems when I built the latest update.
I think that downgrading the Support Library's version is a better solution for now than keeping it at 23 or 24 with some API changes. As @adamantivm points out, than can be performed in another PR. MinSdkVersion remains the same, so that's OK too.
:+1: on merging!

**Pull request merged**
