### PR TITLE
Rearranging and Renabling Hokuyo

### PR DESCRIPTION
**Pull request by stonier**
I forgot to work out a CLA before pull requesting to ros-java, so setting up a pull request now back to rosjava.

@adamantivm if you haven't already done, can you sign a CLA for @damonkohler as described [here](https://github.com/rosjava/rosjava_core)? Then I can merge this back into the rosjava organisation.

Basic gist of what is going on here:
- Moved hokuyo java code out into a java package so java people can make use of that.
- Renabled the android_tutorial_hokuyo package to work with the new gradle environment.

### CODE REVIEW

**Comment by adamantivm** [comment]
I'm currently traveling but will provide the CLA as soon as possible,
probably tomorrow

**Comment by adamantivm** [comment]
Sorry for the delay with this. I am travelling, which makes paperwork execution a bit harder.

We have submitted a corporate CLA covering myself, @tulku and other engineers at our office, so I expect we should be good to go with this and the rest of the contributions we've been submitting recently.

Let us know if anything else is needed.

**Comment by stonier** [comment]
Ok, update us when you get a response.

**Comment by adamantivm** [comment]
@stonier we got response from Google on the CLA's and they told us they're good to go, both for this and for this other PR: https://github.com/ros-java/android_core/pull/10

**Comment by stonier** [comment]
Manually merged in 5b8c714b6e75a8349cf0ea7564a7d52d242625d9

Julian, was your group also responsible for #167?

**Comment by adamantivm** [comment]
@stonier yes. @sebasgm85 is also included in the CLA.

Julian (mobile) | +54(11)5219-0893

**Pull request merged**
