### PR TITLE
Quick demonstration of branching/first pass at RosActivityLifecycle.

### PR DESCRIPTION
**Pull request by chadrockey**
@damonkohler

Here's an example of a pull request.  Is this roughly the right way to do things?  I see some obvious issues, like the abstract void init function requring the nodeMainExecutor.

This pull request should NOT be merged as is.  :)

### CODE REVIEW

**Comment by chadrockey** [comment]
Looks like this could be ready to merge.  Feel free to refactor things around to make things clearer if you see fit.

**Comment by chadrockey** [comment]
@damonkohler I'm having OSRF's @130s take a look at this.

**Comment by chadrockey** [comment]
Oh, and we should merge this into a hydro-devel branch.

**Comment by 130s** [comment]
@chadrockey ok, I'll look at it on Friday (following that common 20% rule).

**Comment by stonier** [comment]
@chadrockey How did you fare with this update chad? Thinking about pulling it in for testing here.

**Comment by 130s** [comment]
@stonier @chadrockey I've just started looking at it yesterday but I have no problem in you working on this.

**Comment by chadrockey** [comment]
Great, @130s.  If I don't hear anything by this next weekend, I'll go ahead and verify functionality and merge it into android_sensors_driver.

**Comment by adamantivm** [comment]
I think this small change would be useful. I think it's important to document well how the RosActivityLifecycle is supposed to work (e.g.: needs lifecycle.onStart(this) on your Activity's onStart(), etc.)

**Comment by stonier** [comment]
Me too, just haven't got around to testing it yet. If you'd like to have a look at it, I can help get it into ros-java/android_core for pulling back here later.

**Pull request closed without merging**
