### PR TITLE
Android Wear OS 2 support (works on Melodic)

### PR DESCRIPTION
**Pull request by roncapat**

### CODE REVIEW

**Review by jubeira — COMMENTED** [review]
Thanks for submitting this @roncapat @lucregrassi !

Before doing a review in depth I have some overall comments / questions (I'm not super familiar with Wear devices, sorry if the questions are a bit silly):
- Is it necessary to bump the `minSdkVersion` to 23? I wouldn't mind bumping it to 19 nowadays, but even being somewhat old devices, 23 [seems a bit high](https://developer.android.com/about/dashboards).
- I think it's a good idea to apply a linter to the codebase, but if you could please apply it in a separate PR with just lint changes, that would help a lot to review the changes so as not to mix things.
- I see that you added a Wear activity which is pretty much the `RosActivity` with some minor adaptations. I'd rather not have two activities that do pretty much the same with different implementations. Do you think it's possible to isolate the functionality for the `RosActivity` in an object, and then compose that object into both `RosActivity` and `RosWearActivity`? That way we would have only one piece of code handling the logic, which would be shared by both classes.

That said, supporting Wear devices sounds like a great contribution!

**Comment by roncapat** [comment]
Hi @jubeira ,

- no, probably we can still keep v19, we'll check and report;
- yes, having duplicate code is not ideal, we will investigate in the best way to deduplicate that

- we'll work to separate linting as a different PR

Thank you for the quick comment! We would be very happy to contribute mainline, so we'll work to satisfy your requests.

**Comment by roncapat** [comment]
@lucregrassi please sign the CLA

**Comment by lucregrassi** [comment]
Done! @roncapat

**Comment by roncapat** [comment]
Deduplicating RosWearActivity and RosActivity code is not straightforward IMHO.
They inherit from two different classes, although related (WearableActivity is derived from Activity)... any idea? I pushed a commit where the only differences of the two files, side-by-side is the swap from Activity to WearableActivity and from MasterChooser to MasterChooserWear.

Notice that also AppCompatRosActivity is duplicated, as an equivalent AppCompatRosWearActivity has to extend RosWearActivity instead of RosActivity

**Comment by roncapat** [comment]
The easiest path would be a code-generation step for generating both versions, since Java Generics do not support something like "extends T" unfortunately.

**Comment by roncapat** [comment]
@jubeira in the last commits, you can see:

- downgrade to minSdkVersion 19
- rollback of the reformats/linting

Then, commit 50bd377 is just a draft for deduplicating code used by both RosWearActivity and RosActivity. In particular, two nested classes have been defined outside, at package level, as generics that take a reference to either a RosActivity or RosWearActivity reference. An interface has been defined, in order to describe what both Activities are required to offer. Only ~50 lines of code were saved, but now the Activites only have very short proxy methods. 
As I said, it's just a draft, and I don't like the fact that some protected stuff now is public for example.

**Comment by jubeira** [comment]
Thanks @roncapat! 
I took another quick look and I don't have a strong opinion against this approach. 

> Only ~50 lines of code were saved, but now the Activites only have very short proxy methods.

Even though the amount looks small, I'd still prefer this than duplicating code.

> As I said, it's just a draft, and I don't like the fact that some protected stuff now is public for example.

The access specifiers is a good point indeed. 
Another approach would be using composition: a third object (separate from `RosActivity` and `RosWearActivity`) would handle all the common functionality between them. Then, both `RosActivity` and `RosWearActivity` would hold a reference to this object, and forward requests to it as needed (perhaps using different parameters where necessary).

This way the methods could still be protected on both top level classes while sharing the code. You could even make this new object implement `RosInterface` to standardize future implementations if they ever come up (`RosAutoActivity`??).

Again, this is not a strong opinion but a slightly higher preference; I would be fine with reviewing the draft in depth as well. Please let me know what you think.

/cc @ernestmc (JIC you have comments to add :slightly_smiling_face: )

**Comment by EliteMasterEric** [comment]
@jubeira what happened to this pull request? What changes still need to be made for it to be merged?

**Comment by roncapat** [comment]
> Another approach would be using composition: a third object (separate from RosActivity and RosWearActivity) would handle all the common functionality between them. Then, both RosActivity and RosWearActivity would hold a reference to this object, and forward requests to it as needed (perhaps using different parameters where necessary).
> 
> This way the methods could still be protected on both top level classes while sharing the code. You could even make this new object implement RosInterface to standardize future implementations if they ever come up (RosAutoActivity??).
> 
> Again, this is not a strong opinion but a slightly higher preference; I would be fine with reviewing the draft in depth as well. Please let me know what you think.

I believe he was waiting for a revision by me implementing his proposals here quoted, but unfortunately, I moved to other projects. The patch itself works as it is now, we use it in various projects in University of Genova, Italy, for different experiments in gesture based interfaces for robotic applications based on commercial smartwatches.

**Comment by roncapat** [comment]
Closing for obsolescence

**Pull request closed without merging**
