### PR TITLE
now compile with android studio!

### PR DESCRIPTION
**Pull request by talregev**
now compile with android studio!
please add.

### CODE REVIEW

**Comment by stonier** [comment]
@talregev, I merged this one across on the command line. Mostly looks great!

I just reverted the directs to your external gradle files, but everything else is in and compiling.

If you want to add to the maven repos list, make a pull request against the code I've hinted at via a comment in the [build.gradle](https://github.com/rosjava/android_core/blob/indigo/build.gradle#L33) file.

**Comment by talregev** [comment]
@stonier 
nice. i see what you did there.

Daniel? can you look at my rosjava_mvn_repo?
https://github.com/talregev/rosjava_mvn_repo

i remove the dependencies that already have a maven repository in the links,
and added more useful library.

**Comment by stonier** [comment]
Wow, busy boy. We should jump on gchat/hangout sometime. I'm just going through a few more things to get it all 'working'.
- One last fix to have an upgraded [message artifact system](http://wiki.ros.org/rosjava/Tutorials/indigo/RosJava Message Artifacts) in indigo
- Add whatever extra maven repos you're using (please make a pull request against [this](https://github.com/rosjava/rosjava_bootstrap/blob/indigo/gradle_plugins/src/main/groovy/org/ros/gradle_plugins/RosPlugin.groovy#L31) for me!)
- Rolling rosjava debs
- Android extras/remocons/apps
- Update android documentation on roswiki

Then let's sync these maven repos.

Then

**Comment by talregev** [comment]
i am not sure i understand you ... :(

sound a lot of work, from the work i am already done here ...

**Comment by stonier** [comment]
Is my TODO list.

Once I finish that, I'll check your maven repo :)

**Comment by talregev** [comment]
oh, ok :+1:

**Comment by talregev** [comment]
i am trying to improve now the bootstrap project. 
already gradle 2.3 is out.

need to update all the project to 2.3 gradle :( :( feeling frustrated

**Comment by stonier** [comment]
Does it need to upgrade? I usually only upgrade it when android studio _forces_ me to upgrade.

What's the bootstrap project? rosjava_bootstrap?

**Comment by talregev** [comment]
yes, it need to upgrade, because it tell you things that will be deprecated in the next gradle (3),
like installApp, so it will be more easy going when we upgrade to gradle 3.

**Comment by talregev** [comment]
https://github.com/rosjava/rosjava_bootstrap

**Pull request closed without merging**
